# Example filter configuration for object detection data filtering

feature_extractor:
  model_name: "facebook/dinov2-base"
  device: "auto"

quality:
  size_filter_enabled: true
  min_size: 10
  max_size_ratio: 0.8
  aspect_ratio_filter_enabled: true
  min_ratio: 0.1
  max_ratio: 10.0

clustering:
  enabled: true
  n_clusters: 50
  samples_per_cluster: 5
  method: "kmeans"

