# Example configuration for updating EXIF GPS data from CSV
# This file demonstrates how to configure the update_gps_from_csv command

# Required parameters
image_folder: "path/to/images"  # Path to folder containing images
csv_path: "path/to/gps_coordinates.csv"  # Path to CSV file with GPS coordinates
output_dir: "path/to/output"  # Output directory for updated images

# Optional parameters
skip_rows: 0  # Number of rows to skip in CSV (e.g., header row)
filename_col: "filename"  # CSV column name for filenames
lat_col: "latitude"  # CSV column name for latitude
lon_col: "longitude"  # CSV column name for longitude
alt_col: "altitude"  # CSV column name for altitude (optional)

# Example CSV format:
# filename,latitude,longitude,altitude
# image1.jpg,40.7128,-74.0060,10.5
# image2.jpg,40.7589,-73.9851,15.2
# image3.jpg,40.7505,-73.9934,8.1 