source_path: D:\workspace\data\general_dataset\tiled-data\coco-dataset\annotations\annotations_val.json
source_format: coco
dataset_name: general_dataset
root: D:\workspace\data\demo-dataset
split_name: val
bbox_tolerance: 5
draw_original_bboxes: true
roi_config:
  random_roi_count: 1
  roi_box_size: 512
  min_roi_size: 32
  dark_threshold: 0.5
  background_class: "background"
  save_format: "jpg"
  quality: 95
  sample_background: false
