source_path: D:\workspace\savmap\coco\annotations\train.json
source_format: coco
dataset_name: savmap
root: D:\workspace\data\demo-dataset
split_name: train
bbox_tolerance: 5
roi_config:
  random_roi_count: 1
  roi_box_size: 224
  min_roi_size: 32
  dark_threshold: 0.5
  background_class: "background"
  save_format: "jpg"
  quality: 95